backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)s

media_folder: "static/uploads"
public_folder: "uploads"

collections:
  - name: 'portfolio'
    label: 'Portfolio'
    folder: 'content/portfolio'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'string' }
      - { label: 'Short Description', name: 'short_description', widget: 'text'}
      - { label: 'Long Description', name: 'long_description', widget: 'text'}
      - label: "Showcase"
        name: "showcase"
        widget: "object"
        fields:
          - {label: "Add to Showcase", name: "add_to_showcase", widget: "boolean", default: false}
          - label: 'Background Image'
            name: 'bg_img'
            widget: 'image'
            choose_url: true
            required: false
            media_library:
              config:
                multiple: false
          - label: 'Floating Image'
            name: 'float_img'
            widget: 'image'
            choose_url: true
            required: false
            media_library:
              config:
                multiple: false
      - { label: "Youtube Video", name: "youtube", widget: "string", default: "null"}
      - label: "Gallery"
        name: "gallery"
        widget: "object"
        fields:
          - label: "Gallery Image"
            name: "images"
            widget: "list"
            fields:
              - label: 'Thumbnail'
                name: 'thumbnail'
                widget: 'image'
                default: 'static/uploads/default.png'
                choose_url: true
                required: false
                media_library:
                  config:
                    multiple: false
              - label: "Big Image"
                name: "big_img"
                widget: 'image'
                default: 'static/uploads/default.png'
                choose_url: true
                required: false
                media_library:
                  config:
                    multiple: false



  - name: 'page_content'
    label: 'Page Content'
    files:
      - label: 'Home Page'
        name: 'home_page'
        file: 'content/pages/home.json'
        editor:
          preview: false
        fields:
          - { label: 'Name', name: 'name', widget: 'string' }
          - { label: 'Intro Paragraph', name: 'intro', widget: 'text' }
          - label: 'Background Image'
            name: 'bg_img'
            widget: 'image'
            choose_url: true
            media_library:
              config:
                multiple: false
      - label: 'Logo'
        name: 'logo'
        file: 'content/pages/logo.json'
        fields:
          - label: 'Main Logo'
            name: 'logo_main'
            widget: 'image'
            choose_url: true
            media_library:
              config:
                multiple: false
          - label: 'Mobile Logo'
            name: 'logo_mobile'
            widget: 'image'
            choose_url: true
            media_library:
              config:
                multiple: false
      - label: 'About Page'
        name: 'about_page'
        file: 'content/pages/about.json'
        editor:
          preview: false
        fields:
          - { label: 'Top Description', name: 'top_desc', widget: 'text' }
          - label: 'Background Image'
            name: 'bg_img'
            widget: 'image'
            choose_url: true
            media_library:
              config:
                multiple: false
          - { label: 'Intro Paragraph', name: 'intro', widget: 'text' }
          - { label: 'Email', name: 'email', widget: 'string'}
          - { label: 'Phone', name: 'phone', widget: 'string'}
          - { label: 'Address', name: 'address', widget: 'string'}