backend:
  name: github
  repo: ashanub/rashmika
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "portfolio"
    create: true
    slug: "{{slug}}"
    media_folder: 'static/uploads/{{slug}}'
    public_folder: '/uploads/{{slug}}'
    path: '{{title}}/{{slug}}'
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - { label: 'Short Description', name: 'short_description', widget: 'text'}
      - { label: 'Long Description', name: 'long_description', widget: 'text'}
      - label: "Showcase"
        name: "showcase"
        widget: "object"
        fields:
          - {label: "Add to Showcase", name: "add_to_showcase", widget: "boolean", default: false}
          - label: 'Background Image'
            name: 'bg_img'
            widget: 'image'
            choose_url: true
            required: false
            media_library:
              config:
                multiple: false
          - label: 'Floating Image'
            name: 'float_img'
            widget: 'image'
            choose_url: true
            required: false
            media_library:
              config:
                multiple: false